spring:
  autoconfigure:
    exclude:
      - org.springframework.boot.autoconfigure.r2dbc.R2dbcAutoConfiguration
      - org.springframework.boot.autoconfigure.data.r2dbc.R2dbcDataAutoConfiguration

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/campus?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: User
    password: 1234
    hikari:
      initializationFailTimeout: -1

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

server:
  port: 8080


ai:
  server:
    url: http://localhost:8081

